package com.xworkz.tostring.runner;
import com.xworkz.tostring.inner.*;

public class MainRunner {
    public static void main(String[] args) {
        Backpack backpack = new Backpack("Nylon", 30, true);
        Bag bag = new Bag("Leather", 25, false);
        Bed bed = new Bed("Queen", "Wood", 20000.0);
        Bicycle bicycle = new Bicycle("Hero", 26, "Mountain");
        Book book = new Book("Java", "James Gosling", 599.0);
        Bottle bottle = new Bottle("Steel", 1, true);
        Bulb bulb = new Bulb("LED", 15, 7.0);
        Calculator calculator = new Calculator("Casio", true, "Scientific");
        Camera camera = new Camera("Canon", 24.2, true);
        Car car = new Car("Toyota", "Innova", 2000000.0);
        Chair chair = new Chair("Plastic", 4.5, false);
        Charger charger = new Charger("Samsung", "Type-C", 25);
        Clipboard clipboard = new Clipboard("A4", "Brown", true);
        Clock clock = new Clock("Wall", "White", true);
        Comb comb = new Comb("Plastic", "Black", 20.0);
        Curtain curtain = new Curtain("Cotton", "Blue", 5.5);
        Cushion cushion = new Cushion("Round", "Red", 3.0);
        Door door = new Door("Wood", "Brown", true);
        DrawingTablet drawingTablet = new DrawingTablet("XP-Pen", 10, true);
        Drone drone = new Drone("DJI", 4, true);
        Earbuds earbuds = new Earbuds("Boat", true, 20);
        Fan fan = new Fan("Crompton", 3, 1200.0);
        FlashDrive flashDrive = new FlashDrive("SanDisk", 64, "USB 3.0");
        Fridge fridge = new Fridge("LG", 300, "Double Door");
        Gamepad gamepad = new Gamepad("Sony", true, "Wireless");
        Glasses glasses = new Glasses("RayBan", "Black", false);
        Globe globe = new Globe("Plastic", 12, "World");
        GraphicsCard graphicsCard = new GraphicsCard("NVIDIA", 8, "RTX 3060");
        Headphones headphones = new Headphones("JBL", true, "Over-Ear");
        Helmet helmet = new Helmet("Vega", "Black", true);
        Highlighter highlighter = new Highlighter("Yellow", "Faber-Castell", true);
        Joystick joystick = new Joystick("Logitech", 2, true);
        Keyboard keyboard = new Keyboard("Mechanical", true, "RGB");
        Keychain keychain = new Keychain("Metal", "Silver", 3.5);
        Laptop laptop = new Laptop("HP", "i5", 8);
        LunchBox lunchBox = new LunchBox("Steel", 2, true);
        Marker marker = new Marker("Whiteboard", "Blue", true);
        Mattress mattress = new Mattress("Foam", "Double", 10000.0);
        Microphone microphone = new Microphone("Blue Yeti", true, "USB");
        Microscope microscope = new Microscope("Olympus", 100, true);
        Microwave microwave = new Microwave("Samsung", 30, true);
        Mirror mirror = new Mirror("Glass", "Oval", false);
        MirrorStand mirrorStand = new MirrorStand("Wood", 5.5, true);
        Mobile mobile = new Mobile("Samsung", "Android", 6.5);
        Mouse mouse = new Mouse("Logitech", true, "Wireless");
        MousePad mousePad = new MousePad("Rubber", "Black", true);
        NailCutter nailCutter = new NailCutter("Steel", 2.5, true);
        Notebook notebook = new Notebook("Classmate", 200, true);
        Pen pen = new Pen("Pilot", "Blue", 14);
        PencilBox pencilBox = new PencilBox("Plastic", "Red", 3);
        Pillow pillow = new Pillow("Cotton", "White", 4);
        Plate plate = new Plate("Steel", "Round", 1);
        PowerBank powerBank = new PowerBank("Mi", 20000, true);
        Printer printer = new Printer("HP", "Inkjet", true);
        Projector projector = new Projector("Epson", true, "HD");
        Refrigerator refrigerator = new Refrigerator("Whirlpool", 240, 4);
        Remote remote = new Remote("Sony", true, "TV");
        RingLight ringLight = new RingLight("LED", 18, true);
        Router router = new Router("TP-Link", true, "Dual Band");
        Scanner scanner = new Scanner("Canon", true, "Flatbed");
        Screwdriver screwdriver = new Screwdriver("Phillips", 6, false);
        SelfieStick selfieStick = new SelfieStick("Aluminum", true, "Bluetooth");
        Shoes shoes = new Shoes("Nike", 9, "Black");
        Skateboard skateboard = new Skateboard("Wood", 4, "Street");
        Smartwatch smartwatch = new Smartwatch("Apple", true, "Series 6");
        Sofa sofa = new Sofa("Leather", 3, true);
        Speaker speaker = new Speaker("JBL", 20, true);
        Stapler stapler = new Stapler("Kangaro", 20, true);
        Sunglasses sunglasses = new Sunglasses("RayBan", "Black", true);
        Table table = new Table("Wood", 4, true);
        Television television = new Television("Sony", 55, "LED");
        Thermometer thermometer = new Thermometer("Digital", true, "Celsius");
        Toothbrush toothbrush = new Toothbrush("OralB", true, "Soft");
        Towel towel = new Towel("Cotton", "White", 2.0);
        Tripod tripod = new Tripod("Aluminum", 150, true);
        Wallet wallet = new Wallet("Leather", "Brown", true);
        WashingMachine washingMachine = new WashingMachine("LG", 7, true);
        Watch watch = new Watch("Fossil", "Analog", true);
        WaterBottle waterBottle = new WaterBottle("Steel", 1, true);
        Whiteboard whiteboard = new Whiteboard("Magnetic", "White", true);
        Wrench wrench = new Wrench("Box-end", 12, true);
        System.out.println(backpack);
        System.out.println(bag);
        System.out.println(bed);
        System.out.println(bicycle);
        System.out.println(book);
        System.out.println(bottle);
        System.out.println(bulb);
        System.out.println(calculator);
        System.out.println(camera);
        System.out.println(car);
        System.out.println(chair);
        System.out.println(charger);
        System.out.println(clipboard);
        System.out.println(clock);
        System.out.println(comb);
        System.out.println(curtain);
        System.out.println(cushion);
        System.out.println(door);
        System.out.println(drawingTablet);
        System.out.println(drone);
        System.out.println(earbuds);
        System.out.println(fan);
        System.out.println(flashDrive);
        System.out.println(fridge);
        System.out.println(gamepad);
        System.out.println(glasses);
        System.out.println(globe);
        System.out.println(graphicsCard);
        System.out.println(headphones);
        System.out.println(helmet);
        System.out.println(highlighter);
        System.out.println(joystick);
        System.out.println(keyboard);
        System.out.println(keychain);
        System.out.println(laptop);
        System.out.println(lunchBox);
        System.out.println(marker);
        System.out.println(mattress);
        System.out.println(microphone);
        System.out.println(microscope);
        System.out.println(microwave);
        System.out.println(mirror);
        System.out.println(mirrorStand);
        System.out.println(mobile);
        System.out.println(mouse);
        System.out.println(mousePad);
        System.out.println(nailCutter);
        System.out.println(notebook);
        System.out.println(pen);
        System.out.println(pencilBox);
        System.out.println(pillow);
        System.out.println(plate);
        System.out.println(powerBank);
        System.out.println(printer);
        System.out.println(projector);
        System.out.println(refrigerator);
        System.out.println(remote);
        System.out.println(ringLight);
        System.out.println(router);
        System.out.println(scanner);
        System.out.println(screwdriver);
        System.out.println(selfieStick);
        System.out.println(shoes);
        System.out.println(skateboard);
        System.out.println(smartwatch);
        System.out.println(sofa);
        System.out.println(speaker);
        System.out.println(stapler);
        System.out.println(sunglasses);
        System.out.println(table);
        System.out.println(television);
        System.out.println(thermometer);
        System.out.println(toothbrush);
        System.out.println(towel);
        System.out.println(tripod);
        System.out.println(wallet);
        System.out.println(washingMachine);
        System.out.println(watch);
        System.out.println(waterBottle);
        System.out.println(whiteboard);
        System.out.println(wrench);

    }
}
